In [ ]:
# 

import pandas as pd
import numpy as np

In [ ]:
# 데이터 로드
from google.colab import drive
drive.mount('/content/drive')

customers_df = pd.read_csv('/content/drive/MyDrive/customers.csv')
orders_df = pd.read_csv('/content/drive/MyDrive/orders.csv')
products_df = pd.read_csv('/content/drive/MyDrive/products.csv')
sales_df = pd.read_csv('/content/drive/MyDrive/sales.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# 데이터 병합
df = pd.merge(customers_df, orders_df, how='inner', on='customer_id')
df = pd.merge(df, sales_df, how='inner', on='order_id')
df = pd.merge(df, products_df, how='inner', left_on='product_id', right_on='product_ID')
df.head()

customer_id  customer_name    gender  age                    home_address  \
0            1  Leanna Busson    Female   30  8606 Victoria TerraceSuite 560   
1            1  Leanna Busson    Female   30  8606 Victoria TerraceSuite 560   
2           81  Lanny Wardale    Female   30     4870 Jackson SummitApt. 538   
3          258  Mira Heinonen    Female   62     2719 Dietrich KnollApt. 175   
4          432  Ettie Gonnely  Bigender   34      6172 Andrew AvenueApt. 194   

   zip_code            city               state    country  order_id  ...  \
0      5464   Johnstonhaven  Northern Territory  Australia       455  ...   
1      5464   Johnstonhaven  Northern Territory  Australia       455  ...   
2      1915  Spencerborough   Western Australia  Australia       863  ...   
3      1252    South Declan          Queensland  Australia       793  ...   
4      7029      North Cody            Victoria  Australia       939  ...   

   quantity_x total_price product_ID  product_type  product_name  size  \
0           3         318        211         Shirt      Chambray     S   
1           2         182        783        Jacket      Pullover     L   
2           1          91        783        Jacket      Pullover     L   
3           3         273        783        Jacket      Pullover     L   
4           2         182        783        Jacket      Pullover     L   

   colour  price  quantity_y                                  description  
0     red    105          72      A red coloured, S sized, Chambray Shirt  
1  yellow    114          43  A yellow coloured, L sized, Pullover Jacket  
2  yellow    114          43  A yellow coloured, L sized, Pullover Jacket  
3  yellow    114          43  A yellow coloured, L sized, Pullover Jacket  
4  yellow    114          43  A yellow coloured, L sized, Pullover Jacket  

[5 rows x 26 columns]

In [ ]:
df['one'] = 1 # one이라는 column 생성, 값 1삽입
df.head() 

customer_id  customer_name    gender  age                    home_address  \
0            1  Leanna Busson    Female   30  8606 Victoria TerraceSuite 560   
1            1  Leanna Busson    Female   30  8606 Victoria TerraceSuite 560   
2           81  Lanny Wardale    Female   30     4870 Jackson SummitApt. 538   
3          258  Mira Heinonen    Female   62     2719 Dietrich KnollApt. 175   
4          432  Ettie Gonnely  Bigender   34      6172 Andrew AvenueApt. 194   

   zip_code            city               state    country  order_id  ...  \
0      5464   Johnstonhaven  Northern Territory  Australia       455  ...   
1      5464   Johnstonhaven  Northern Territory  Australia       455  ...   
2      1915  Spencerborough   Western Australia  Australia       863  ...   
3      1252    South Declan          Queensland  Australia       793  ...   
4      7029      North Cody            Victoria  Australia       939  ...   

   total_price product_ID product_type  product_name  size  colour  price  \
0          318        211        Shirt      Chambray     S     red    105   
1          182        783       Jacket      Pullover     L  yellow    114   
2           91        783       Jacket      Pullover     L  yellow    114   
3          273        783       Jacket      Pullover     L  yellow    114   
4          182        783       Jacket      Pullover     L  yellow    114   

   quantity_y                                  description one  
0          72      A red coloured, S sized, Chambray Shirt   1  
1          43  A yellow coloured, L sized, Pullover Jacket   1  
2          43  A yellow coloured, L sized, Pullover Jacket   1  
3          43  A yellow coloured, L sized, Pullover Jacket   1  
4          43  A yellow coloured, L sized, Pullover Jacket   1  

[5 rows x 27 columns]

In [ ]:
# 사용자별로 구매한 상품 정보(1 or 0) 테이블 생성
# Row(customer_Id) & Column(product_ID) : 1 or 0
df = df.pivot_table(index='customer_id', columns = 'product_ID', values = 'one').fillna(0)
df.head()

product_ID   1     2     3     4     5     6     7     8     9     10    ...  \
customer_id                                                              ...   
1             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
7             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
10            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
11            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
12            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

product_ID   1249  1250  1252  1253  1254  1255  1256  1257  1258  1259  
customer_id                                                              
1             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
7             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  
10            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
11            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
12            0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 1233 columns]

In [ ]:
# df의 모든 행과 열을 numpy배열로
shopping_metrix = df.iloc[:, : ].values

In [ ]:
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# 학습 조건 설정
BATCH_SIZE = 64
EPOCHS = 100

In [ ]:
from torch.utils.data import Dataset # 사용자 정의 데이터셋을 만들기 위함
from torch.utils.data import DataLoader # 데이터셋을 미니배치로 나누고 로딩

class CustomDataset(Dataset):

  # 데이터 정의
  def __init__(self, x_data): # 초기화
    self.x_data = x_data

  # 이 데이터 셋의 총 데이터 수
  def __len__(self):
    return len(self.x_data)

  # 어떠한 idx를 받았을 때 그에 맞는 데이터를 반환
  def __getitem__(self, idx):
      x = torch.FloatTensor(self.x_data[idx]) # 텐서로 반환
      return x

In [ ]:
# AutoEncoder 모델 설계
class Encoder(nn.Module): # nn 모듈을 상속받아 기본적인 기능을 사용가능
    def __init__(self):
        super(Encoder,self).__init__()
        self.fc1_1 = nn.Linear(1233, 256) # 완전연결 계층
        self.fc1_2 = nn.Linear(1233, 256) # 완전연결 계층
        self.relu = nn.ReLU() # 활성화 함수
                        
    def encode(self, x):
        mu = self.relu(self.fc1_1(x)) # 인코딩된 평균
        log_var = self.relu(self.fc1_2(x)) # 로그 분산
                
        return mu,log_var
    
    def reparametrize(self, mu, log_var): # 잠재 변수를 샘플링
        std = log_var.mul(0.5).exp_() # 표준편차 계산
        eps = torch.FloatTensor(std.size()).normal_().to(mu.device) # 정규분포를 따르는 샘플링
    
        return eps.mul(std).add_(mu) # 잠재 변수 z 반환 : Sample * 분산 + 평균
    
    def forward(self,x): # 순전파
        mu, log_var = self.encode(x)
        reparam = self.reparametrize(mu,log_var)
        
        return mu,log_var,reparam # 분포의 평균과 분산, Reparameterization Trick한 z값 반환
        
encoder = Encoder() 

In [ ]:
class Decoder(nn.Module):
    def __init__(self):
        super(Decoder,self).__init__()
        self.fc1 = nn.Linear(256, 1233) # 완전연결 계층
        self.simoid = nn.Sigmoid() # 활성화 함수 sigmoid
    
    def forward(self,x): # 순전파
        out = self.fc1(x) # z값으로 output 생성
        out = self.simoid(out) # 0~1 값으로 변환
        
        return out # New Data 반환
        
decoder = Decoder()

In [ ]:
reconstruction_function = nn.MSELoss(size_average=False) # 평균 제곱 오차

def loss_function(recon_x, x, mu, log_var): # 손실함수 정의
    MSE = reconstruction_function(recon_x, x) # 손실 계산

    KLD_element = mu.pow(2).add_(log_var.exp()).mul_(-1).add_(1).add_(log_var) # KL발산 최적화를 통해 기본 관계 및 패턴을 학습
    KLD = torch.sum(KLD_element).mul_(-0.5)

    return MSE + KLD # 총 손실 반환

parameters = list(encoder.parameters())+ list(decoder.parameters()) # 인코더와 디코더의 파라미터를 묶음
optimizer = torch.optim.Adam(parameters, lr=0.0005) # 옵티마이저, 학습률 지정
     

/usr/local/lib/python3.10/dist-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [ ]:
def train(encoder, decoder, train_loader):
  encoder.train() # 학습 모드로 설정
  decoder.train()
  train_loss = 0 # 손실 초기화

  for feature in train_loader: # 순회
    feature = feature
    optimizer.zero_grad() # 옵티마이저 기울기 초기화
    mu,log_var,reparam = encoder(feature) # 인코더에 feature 전달, 평균, 분산, 잠재 변수 얻음
    output = decoder(reparam) # 잠재 변수로 output 얻음
    loss = loss_function(output, feature, mu, log_var) # 손실 구함
    loss.backward() # 역전파-기울기 구함
    optimizer.step() # 파라미터 업데이트
    
    train_loss += loss.item() # 학습 손실 업데이트

  train_loss /= len(train_loader) # 평균 손실
  return train_loss # 출력하기 위해 반환

In [ ]:
def evaluate(encoder, decoder, train_loader):
  encoder.eval() # 평가 모드로 설정
  decoder.eval() # 파라미터가 업데이트 되지 않도록 함
  result = [] # 결과 저장할 리스트
 
  with torch.no_grad(): # 기울기 계산 비활성화 - 평가 단계에서는 필요 없음

    for feature in train_loader: # train_loader 순회
      feature = feature 
      mu,log_var,reparam = encoder(feature) # encoder
      output = decoder(reparam) # decoder
      result.append(output.cpu().numpy()) # 데이터 결과 집합에 저장

  result = np.concatenate(result) # 결과 리스트 연결하여 하나의 배열로 변환
  return result

In [ ]:
train_dataset = CustomDataset(shopping_metrix) # 입력 데이터셋 얻기

train_loader = DataLoader( # train_loader 생성, 데이터를 batch_size로 나누어 공급
  train_dataset,
  batch_size = BATCH_SIZE, # 64
  shuffle = False, # 데이터 증강 없음
  drop_last = False)

for epoch in range(1, EPOCHS + 1): # epochs만큼 반복
  train_loss = train(encoder, decoder, train_loader) # 학습 손실 계산
  print(f"\n[EPOCH: {epoch}], \tTrain Loss: {train_loss:.4f}") # 현재 epochs 및 손실 출력
     

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
 

In [ ]:
# 평가
result = evaluate(encoder, decoder, train_loader)
result # 확률분포 형태
     

array([[0.03069222, 0.05032148, 0.05518727, ..., 0.08618739, 0.05150977,
        0.0479849 ],
       [0.03924893, 0.03202129, 0.03763701, ..., 0.0252059 , 0.05673806,
        0.06000235],
       [0.05233138, 0.03647131, 0.04950068, ..., 0.03948332, 0.03818599,
        0.05600806],
       ...,
       [0.00915711, 0.00660693, 0.0062754 , ..., 0.00438441, 0.0097509 ,
        0.00761987],
       [0.03364165, 0.01052491, 0.00991702, ..., 0.01065422, 0.01690116,
        0.013042  ],
       [0.00126728, 0.00195483, 0.00112337, ..., 0.0019663 , 0.00187913,
        0.00323954]], dtype=float32)

In [ ]:
# df의 상품 이름만 리스트로 추출
product_li = df.columns.tolist() 

# 산 상품은 제외(-1로 변경) : 구매하지 않은 상품만 추천하기 위함
result[shopping_metrix >= 1] = -1 

In [ ]:
# 추천 상품 리스트 생성
recommend_li = [] 
# result(확률)에 대해 가장 높은 값(argmax)를 가지는 상품을 추가
for i in result.argmax(axis=1): 
  recommend_li.append(product_li[i])

In [ ]:
recommend_df = pd.DataFrame() # pd 빈 데이터프레임 생성
recommend_df['user_id'] = df.index.tolist() # user_id 컬럼 생성 : 1부터 부여
recommend_df['product_ID'] = recommend_li # product 컬럼 생성 : 추천 상품 입력
recommend_df = pd.merge(recommend_df, products_df, how='inner', on='product_ID')
recommend_df.head(10) # 각 유저에게 가장 추천하는 상품 출력

user_id  product_ID product_type       product_name size  colour  price  \
0        1         681       Jacket              Parka    S   green    119   
1        7         385        Shirt    Casual Slim Fit   XS     red    113   
2      528         385        Shirt    Casual Slim Fit   XS     red    113   
3       10        1247     Trousers  Tracksuit Bottoms    M    blue     91   
4       11        1066     Trousers            Joggers    S   green     94   
5       12         200        Shirt      Camp Collared   XS  indigo    112   
6       13        1060     Trousers            Joggers   XS  yellow     94   
7       15        1010     Trousers               Wool   XS  violet    111   
8       16         740       Jacket            Peacoat   XS  orange    102   
9      156         740       Jacket            Peacoat   XS  orange    102   

   quantity                                        description  
0        62            A green coloured, S sized, Parka Jacket  
1        49    A red coloured, XS sized, Casual Slim Fit Shirt  
2        49    A red coloured, XS sized, Casual Slim Fit Shirt  
3        61  A blue coloured, M sized, Tracksuit Bottoms Tr...  
4        76        A green coloured, S sized, Joggers Trousers  
5        64   A indigo coloured, XS sized, Camp Collared Shirt  
6        62      A yellow coloured, XS sized, Joggers Trousers  
7        80         A violet coloured, XS sized, Wool Trousers  
8        78        A orange coloured, XS sized, Peacoat Jacket  
9        78        A orange coloured, XS sized, Peacoat Jacket

In [ ]:
# 원본 데이터
df2 = pd.merge(customers_df, orders_df, how='inner', on='customer_id')
df2 = pd.merge(df2, sales_df, how='inner', on='order_id')
df2 = pd.merge(df2, products_df, how='inner', left_on='product_id', right_on='product_ID')
# df2.head()

In [ ]:
# 이력을 추출하기 위한 테이블
record = pd.DataFrame({'customer_id':[], 'product_ID':[], 'product_type':[], 'product_name':[], 'size':[], 'colour':[], 'description':[]})

idx = 1
for i in df2.index:
  if df2.iloc[i, 0] == 7: # customer_id 7이 구매한 이력을 탐색
    record.loc[idx] = df2.loc[i, ['customer_id', 'product_ID', 'product_type', 'product_name', 'size', 'colour', 'description']]
    idx = idx + 1

record

customer_id product_ID product_type       product_name size  colour  \
1           7       1118     Trousers            Cropped    L  violet   
2           7       1259     Trousers  Tracksuit Bottoms   XL  violet   
3           7        811       Jacket          Shearling    S  orange   
4           7        408        Shirt    Casual Slim Fit    L    blue   
5           7       1010     Trousers               Wool   XS  violet   

                                         description  
1       A violet coloured, L sized, Cropped Trousers  
2  A violet coloured, XL sized, Tracksuit Bottoms...  
3       A orange coloured, S sized, Shearling Jacket  
4    A blue coloured, L sized, Casual Slim Fit Shirt  
5         A violet coloured, XS sized, Wool Trousers

# 결과

#### 고객의 구매 이력을 바탕으로 가장 유사한 상품을 추천
#### 데이터셋이 작아서 그렇게 좋은 효과를 얻지는 못한 것 같음
#### 각 상품에 대한 고객의 평가가 어떠한지에 대한 결과는 반영되지 않았음